ja:
  errors:
    messages:
      already_taken: "は使用できません"
